### ISSUE TITLE
Doesn't work anymore in current Nim

### ISSUE THREAD

**Issue by def-** [flyx/emerald#16]
Current Nim from devel branch, `import emerald` throws this:

```
/home/deen/.nimble/pkgs/emerald-0.2.2/emerald/html.nim(299, 32) Error: expression 'quit "[emerald] " & lineInfo(node) & ": Unexpected " &
    "command (expected replace, prepend or append)" & ": \"" &
    $ident_name(node[0]) & "\"", 1' is of type 'NimNode' and has to be discarded
```

**Comment by zedeus** [comment]
After the fixes in august the version number didn't get raised, so nimble still pulls the old version. @flyx please bump the version number

**Comment by flyx** [comment]
Version number bumped (sorry for the *really* long ping).
